# This is a basic workflow to help you get started with Actions

name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Rust buruma!
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test --verbose
