# This is a basic workflow to help you get started with Actions

name: rust

on:
  [ push, pull_request ]

  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 8 ]
        zk-version: [ 3.6.1, 3.6.2, 3.6.3, 3.7.0 ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test code
        run: make test ZK_VERSION=${{ matrix.zk-version }}
